package com.ambity.dto;

public class Tb1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1.id
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb1.value
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1.id
     *
     * @return the value of tb1.id
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1.id
     *
     * @param id the value for tb1.id
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb1.value
     *
     * @return the value of tb1.value
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb1.value
     *
     * @param value the value for tb1.value
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}