spring:
  kafka:
    producer:
      bootstrap-servers: 10.238.148.30:9092
      acks: 1
      batch-size: 16384
      retries: 3
      buffer-memory: 33554432
#      auto-offset-reset: earliest
server:
  port: 8082
