spring:
  kafka:
    producer:
      bootstrap-servers: 10.238.153.80:9092
      acks: 1
      batch-size: 16384
      retries: 3
      buffer-memory: 33554432

    consumer:
      group-id: test
      bootstrapServers: 10.238.153.80:9092
      enable-auto-commit: false
      auto-offset-reset: earliest
server:
  port: 8082
