server:
  port: 8083
eureka:
  client:
    registryFetchIntervalSeconds: 30
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true
#关闭某个微服务的服务实例名称映射,若想关闭多个通过逗号隔开
zuul:
  prefix: /api
  sensitive-headers:
