
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
    preferIpAddress: true
server:
  port: 8082
#  servlet:
#    context-path: /client2
ribbon:
  eureka:
    enabled: true
#  eager-load:    #饥饿加载模式
#    enabled: true
#    clients: pay-bestpay-code
feign:
  hystrix:
   enabled: false    #feign客户端对Hystrix支持，默认是关闭
hystrix:
  config:
    stream:
      maxConcurrentConnections: 10
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 50000

    'Client1Feign#client1()':
      threadPoolKeyOverride: 'Client1Feign#client1()'
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 45000
  threadpool:
mybatis:
  mapper-locations: classpath:mapper/*.xml

client1:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 最空闲连接策略
    ConnectTimeout: 5000 #请求连接超时时间
    ReadTimeout: 10000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 1 #切换实例的重试次数
    MaxAutoRetries: 0 #对当前实例的重试
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource1:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ambity