package com.ambity.mapper;

import com.ambity.dto.Tb1;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface Tb1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    int insert(Tb1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    int insertSelective(Tb1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    Tb1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    int updateByPrimaryKeySelective(Tb1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb1
     *
     * @mbg.generated Sat Dec 05 16:56:47 CST 2020
     */
    int updateByPrimaryKey(Tb1 record);
}